# Generated by Django 5.0 on 2023-12-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='UserName')),
                ('email', models.EmailField(max_length=254, verbose_name='UserEmail')),
                ('password', models.CharField(max_length=50, verbose_name='UserPass')),
            ],
        ),
    ]
