# Generated by Django 5.0 on 2023-12-18 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'UserData', 'verbose_name_plural': 'UserDatas'},
        ),
    ]
