# Generated by Django 4.2.7 on 2023-12-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_alter_userdata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.TextField(verbose_name='UserName'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.TextField(verbose_name='UserName'),
        ),
    ]
