# Generated by Django 5.0 on 2024-02-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0004_alter_userdata_options_remove_userdata_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='usertype',
            field=models.BooleanField(default=True, verbose_name='User Type'),
        ),
    ]
